### ISSUE TITLE
An error occurred after updating the plug-in

### ISSUE THREAD

**Issue by alex13by** [if-ai/ComfyUI-IF_AI_tools#124]
After the update, two directories with the same name appear in the plug-in directory. Even if the plug-in is uninstalled and re-installed after uninstallation, two directories will appear, but it can start, but the following error message will be displayed:
![image](https://github.com/user-attachments/assets/6c282aaa-1441-4af0-8db0-109b62afe400)

[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 965, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 382, in __init__
    self.stop_strings = self.load_presets(self.stop_file)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 423, in load_presets
    with open(file_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_IF_AI_tools\\IF_AI\\presets\\stop_strings.json'

D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 965, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 382, in __init__
    self.stop_strings = self.load_presets(self.stop_file)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 423, in load_presets
    with open(file_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_IF_AI_tools\\IF_AI\\presets\\stop_strings.json'

**Comment by huwhitememes** [comment]
Same here. Import error in the comfy terminal. I just keep deleting and reinstalling. Not sure what is happening.

**Comment by dzy1128** [comment]
Same error,have you solved it?

**Comment by hungyanng** [comment]
作者的地址写错了，太多了，所以将所有文件复制到新生成文件夹中就可以了

**Comment by dzy1128** [comment]
能麻烦您讲的细一点吗，将旧的文件夹里的东西复制到新的文件里面吗？还是其他的什么

**Comment by if-ai** [comment]
sorry I think it should be solved now

**Comment by alex13by** [comment]
> sorry I think it should be solved now

Just updated with a new issue:

[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 965, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 383, in __init__
    self.assistants = self.load_presets(self.assistants_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 424, in load_presets
    presets = json.load(f)
              ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbe in position 5968: illegal multibyte sequence

Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 965, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 383, in __init__
    self.assistants = self.load_presets(self.assistants_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 424, in load_presets
    presets = json.load(f)
              ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbe in position 5968: illegal multibyte sequence

Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence
Error loading presets from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence

**Comment by if-ai** [comment]
@alex13by did you edit the negative prompts? there must be an error on the format or an emoji some kind of character that is not compatible 

`D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence`

Download the neg_prompts.json file again and place it on the presets folder or fix the edit

**Comment by gee666** [comment]
@if-ai @alex13by  I resolved the error by removing these symbols from the neg_promps file (they are present in the repository)

![ksnip_20241116-050322](https://github.com/user-attachments/assets/d70d63f2-dc4f-4ec7-b676-8170155d703a)

**Comment by gee666** [comment]
@if-ai unfortunately it still doesn't work for me, I can't understand the reason right now, would you please be so kind to give an advice. After resolving the previous error, now I have this (2 next screenshots):

![ksnip_20241116-050909](https://github.com/user-attachments/assets/bb88fb73-3b2c-43ae-9b67-3c0b38f7d009)
![ksnip_20241116-050837](https://github.com/user-attachments/assets/9b54e5c4-3af1-46b9-baa7-cd470434322c)

**Comment by alex13by** [comment]
> @if-ai @alex13by I resolved the error by removing these symbols from the neg_promps file (they are present in the repository)
>
>! [ksnip_20241116-050322](https://private-user-images.githubusercontent.com/129552948/386843294-d70d63f2-dc4f-4ec7-b676-81 70155d703a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50 LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTk0NzMsIm5iZiI6MTczMTc1OTE3MywicGF0aCI6Ii8xMjk1NTI5NDgvMzg2ODQzMjk0LWQ3MGQ2M2Yy LWRjNGYtNGVjNy1iNjc2LTgxNzAxNTVkNzAzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNP RFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMjEyNTNaJlgtQW16 LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGQ0ZDYwMDUyOGZmMzMwOTYwMWFkNjY1YzFlMWI0YjkyNGIxM2MyMDk0NDBhZjM5NDgxN2MwNGZkOTY3 MDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MhAhW7fQjVYcP00BvnvRZnraqwILblsdHsct1tx9gIc)

Yes, that part of the problem has been solved, but there are other problems

[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 965, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 383, in __init__
    self.assistants = self.load_presets(self.assistants_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 424, in load_presets
    presets = json.load(f)
              ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbe in position 5968: illegal multibyte sequence

D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 965, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 383, in __init__
    self.assistants = self.load_presets(self.assistants_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 424, in load_presets
    presets = json.load(f)
              ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbe in position 5968: illegal multibyte sequence

**Comment by alex13by** [comment]
> @alex13by did you edit the negative prompts? there must be an error on the format or an emoji some kind of character that is not compatible
> 
> `D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x86 in position 185: illegal multibyte sequence`
> 
> Download the neg_prompts.json file again and place it on the presets folder or fix the edit

This issue arose after I completely re-cloned it, confirming that no modifications had been made

**Comment by if-ai** [comment]
@alex13by and @gee666 I am introducing a lot of features I'll be working on fixing this issues today sorry for the inconvinience and thank you for pointing them out.

**Comment by gee666** [comment]
@if-ai thank you, will wait.
I absolutely love your nodes, thank you for your work.

**Comment by DreamLoveBetty** [comment]
Changing the file encoding of assistants.json,neg_prompts.json to GBK encoding can solve the problem. The routine operation is: use notepad to open the error original json file, save as ascii encoding, and then select gbk.
